name: "Runs Unittest"
description: "Runs the unittest module"

# inputs:
#   registry_username:
#     description: “Username for image registry”
#     required: true
#   registry_password:
#     description: “Password for image registry”
#     required: true

runs:
  using: "composite"
  steps:
    - run: |
        echo "testing ..."
        ehco "DONE"
