name: "Build on ARM"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspios_lite_arm64:latest
        commands: |
            curl -sL https://deb.nodesource.com/setup_18.x | sudo bash -
            sudo apt install nodejs
            npm gi yarn
            yarn run init
            yarn run build
