name: "Build on ARM"

on:
  push:
    branches:
      - 'testing-build'

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          copy_artifact_path: dist/react-pywebview-boilerplate
          copy_artifact_dest: .
          base_image: raspios_lite:latest
          cpu: cortex-a7
          cpu_info: raspberrypi_3b
          image_additional_mb: 4096
          commands: |
              sudo apt update
              sudo apt install python3-pip -y
              pip3 install virtualenv
              curl -sL https://deb.nodesource.com/setup_18.x | sudo bash -
              sudo apt install nodejs -y
              npm install --global yarn
              yarn run init
              export CI=false
              yarn run build
      - uses: actions/upload-artifact@v3
        with:
          name: devbuild
          path: react-pywebview-boilerplate

  prerelease:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: devbuild   
      - run: ls -al
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            react-pywebview-boilerplate
