name: "Build on ARM"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          copy_artifact_path: /tmp/output
          copy_artifact_dest: .
          base_image: raspios_lite_arm64:latest
          image_additional_mb: 4096
          commands: |
              sudo apt update
              sudo apt install python3-pip -y
              pip3 install virtualenv
              curl -sL https://deb.nodesource.com/setup_18.x | sudo bash -
              sudo apt install nodejs -y
              npm install --global yarn
              yarn run init
              yarn run build
              mv dist/react-pywebview-boilerplate /tmp/output

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: output
