name: Create Tag

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: read
  
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: phish108/autotag-action@v1.1.64
      id: tagger
      with:
        github-token: ${{ secrets.GITHUB_TOKEN}}
        with-v: "true"
        branch: main
        bump: major
        release-branch: main
        dry-run: 'true'
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.tagger.outputs.new-tag }}"
          prerelease: false
      

