name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: phish108/autotag-action@v1.1.55
      with:
        github-token: ${{ secrets.GITHUB_TOKEN}}
