name: "release"

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: read

jobs:
  release:
    if: github.event.pull_request.merged == true
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.pull_request.title }}"
          prerelease: false
          # title: "Development Build"
          files: |
            *.py
