name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   args: |
        #     darwin-amd64.zip
        #     linux-amd64.zip
        #     windows-amd64.zip

# name: Release
#
#
#
# on:
#   push:
#     branches:
#       - main
# jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - name: Setup Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12
#       - name: Install dependencies
#         run: npm ci
#       - name: Release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#         run: npx semantic-release

# name: "release"
#
# on:
#   pull_request:
#     branches:
#       - main
#     types:
#       - closed
#
# permissions:
#   id-token: write
#   contents: write
#   packages: write
#   pull-requests: read
#
# jobs:
#   release:
#     if: github.event.pull_request.merged == true
#     name: "Release"
#     runs-on: "ubuntu-latest"
#
#     steps:
#       - name: "Build & test"
#         run: |
#           echo "done!"
#
#       - uses: "marvinpinto/action-automatic-releases@latest"
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           automatic_release_tag: "${{ github.event.pull_request.title }}"
#           prerelease: false
#           # title: "Development Build"
#           files: |
#             *.py
