name: Update Documentation

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [develop]

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  pull-requests: write
  contents: write

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - 'cnlp/**'

  build-docs:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Build
        run: |
          make

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: docs/**
          commit-message: "docs: Auto-generated Documentation"
          branch: docs/autogenerate
          delete-branch: true
          title: 'docs: Aggiornata documentazione'
          body: |
            Generata documentazione in automatico
            - Aggiornata documentazione
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: documentation
          draft: false



