name: "Unittests"

on:
  push:
    branches:
      - develop
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  run-tests:
    uses: ./.github/workflows/unittest-core.yml

